# Generated by Django 2.2.5 on 2020-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_survey_complete', models.BooleanField(default=False)),
                ('last_survey_save', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
