# Generated by Django 2.2.5 on 2020-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_surveyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='token',
            field=models.CharField(default='gsz7', max_length=4),
        ),
    ]
