# Generated by Django 2.2.5 on 2020-05-28 16:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200528_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.CharField(default=accounts.models.get_token, max_length=4),
        ),
    ]
