# Generated by Django 2.2.5 on 2020-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200528_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.CharField(default='6481', max_length=4),
        ),
    ]
