# Generated by Django 2.2.5 on 2020-05-28 16:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200528_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.CharField(default=accounts.models.get_token, max_length=4),
        ),
    ]
