# Generated by Django 2.2.5 on 2020-05-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choiceType',
        ),
    ]
