# Generated by Django 2.2.5 on 2020-05-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200528_1234'),
        ('survey', '0004_auto_20200528_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='surveyuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.SurveyUser'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'surveyuser')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
