# Generated by Django 2.2.5 on 2020-05-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200528_1234'),
        ('survey', '0005_auto_20200528_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='surveyuser',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'user')},
        ),
    ]
